services:
  spring-app:
    build: ./spring
    container_name: spring-app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHON_BASE_URL=http://fastapi:8000
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/piggybank
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=soup
    env_file:
      - ./spring/.env
    depends_on:
      - fastapi
      - db
      - redis
    networks:
      - piggybank-network

  fastapi:
    build: ./python
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./python/rules.xlsx:/app/rules.xlsx  # 개발 중 실시간 반영 가능
    depends_on:
      - db
    networks:
      - piggybank-network

  db:
    image: mysql:8.1
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: soup
      MYSQL_DATABASE: piggybank
      MYSQL_USER: piggybank_user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - piggybank-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - piggybank-network

networks:
  piggybank-network:
    driver: bridge

volumes:
  db_data: